# Generated by Django 5.2.1 on 2025-05-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessEnthusiast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('fitness_goals', models.TextField()),
                ('preferred_workout_time', models.CharField(max_length=50)),
                ('preferred_workout_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessEnthusiatSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_enthusiast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.fitnessenthusiast')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
