# Generated by Django 5.2.1 on 2025-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='exercise_image/')),
                ('video', models.FileField(upload_to='exercise_video/')),
                ('equipment', models.CharField(max_length=100)),
            ],
        ),
    ]
