# Generated by Django 5.2.1 on 2025-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('calories', models.PositiveIntegerField(help_text='Total calories per day')),
                ('protein', models.FloatField(help_text='Protein in grams per day')),
                ('carbs', models.FloatField(help_text='Carbohydrates in grams per day')),
                ('fats', models.FloatField(help_text='Fats in grams per day')),
                ('duration_days', models.PositiveIntegerField(help_text='Duration of the plan in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
